title: 猫说
email: 路虽远，行则必至。
description: >
  Mekyll - Medium-style theme for Jekyll
baseurl: "/catsaid" # the subpath of your site, e.g. /blog
url: "https://oldpubcat.github.io" # the base hostname & protocol for your site
postCount: 5 # the number of posts on the "index" page

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink   : /:year/:title/
source: ./
destination: ./_site

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
